#oauth2:
#  userAuthorizationUri: "https://eu:battle:net/oauth/authorize"
#  accessTokenUri: "https://eu.battle.net/oauth/token"
#  tokenName: "access_token"
#  clientId: "28031be62ca84e78a9ea4fb18e818c4c"
#  clientSecret: "Y5KW9l5l34ybu8zUovSj22wb58SxS7Fj"

# ??? ????????????? ?????????? ?????.

#    oauth2.userAuthorizationUri=https://eu.battle.net/oauth/authorize
#    oauth2.=https://eu.battle.net/oauth/token
#    oauth2.tokenName=access_token
#    oauth2.clientId=${WC_BLIZZARD_API_CLIENT_ID}
#    oauth2.clientSecret=${WC_BLIZZARD_API_CLIENT_SECRET}


#?????? ?? ??????? https://github.com/christopheml/wow-completionist

server:
  port: 3100
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  mail:
    host: smtp.yandex.ru
    username: WowVendorTeamHelper@yandex.ru
    password: xmmlrqqbdfddjrbc
    port: 465
    protocol: smtps
  kafka:
    consumer:
      group-id: 223
    bootstrap-servers: localhost:9092
mail:
  debug: true
logging:
  level:
    org.springframework.transaction: DEBUG

