oauth2:
  clientId: "28031be62ca84e78a9ea4fb18e818c4c"
  clientSecret: "Y5KW9l5l34ybu8zUovSj22wb58SxS7Fj"

jwt:
  secret: "kfvdkfvnoeh981jt05jgimovi98rvgh913hg3g01n3okwedvn93h"
  lifetime: "3600000"

server:
  port: 3100
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/postgres
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  mail:
    host: smtp.yandex.ru
    username: WowVendorTeamHelper@yandex.ru
    password: xmmlrqqbdfddjrbc
    port: 465
    protocol: smtps
mail:
  debug: true
logging:
  level:
    org.springframework.transaction: DEBUG

my-config:
  url-activate: http://localhost:3100/activate/
